import crypto from 'node:crypto';
import { z } from 'zod';
import { pool, withTransaction } from '../db.js';
import { AppError } from '../errors.js';

const nodeSchema=z.object({id:z.string().min(1).max(80),type:z.enum(['scene','choice','condition','reward','ending']),title:z.string().max(160),text:z.string().max(3000).default(''),x:z.number().default(0),y:z.number().default(0),config:z.record(z.unknown()).default({})});
const edgeSchema=z.object({id:z.string().min(1).max(100),from:z.string(),to:z.string(),label:z.string().max(120).default(''),condition:z.record(z.unknown()).optional()});
export const dialogGraphSchema=z.object({startNodeId:z.string().min(1),nodes:z.array(nodeSchema).min(1).max(500),edges:z.array(edgeSchema).max(1500),metadata:z.record(z.unknown()).default({})}).superRefine((graph,ctx)=>{const ids=new Set(graph.nodes.map(n=>n.id));if(!ids.has(graph.startNodeId))ctx.addIssue({code:'custom',message:'Стартовый узел отсутствует',path:['startNodeId']});for(const [i,e]of graph.edges.entries())if(!ids.has(e.from)||!ids.has(e.to))ctx.addIssue({code:'custom',message:'Связь указывает на отсутствующий узел',path:['edges',i]});});
export async function listDocuments(){return (await pool.query(`SELECT d.*,a.username created_by_name,u.username updated_by_name FROM content_documents d LEFT JOIN admins a ON a.id=d.created_by LEFT JOIN admins u ON u.id=d.updated_by ORDER BY d.updated_at DESC`)).rows;}
export async function createDocument(adminId:string,input:{slug:string;title:string;contentType:string;graph:unknown;changeNote?:string}){const graph=dialogGraphSchema.parse(input.graph);const id=crypto.randomUUID();await withTransaction(async client=>{await client.query(`INSERT INTO content_documents(id,slug,content_type,title,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$5)`,[id,input.slug,input.contentType,input.title,adminId]);await client.query(`INSERT INTO content_versions(document_id,version,graph,change_note,created_by) VALUES($1,1,$2,$3,$4)`,[id,JSON.stringify(graph),input.changeNote??'Первая версия',adminId]);});return{id,version:1};}
export async function saveDraft(adminId:string,documentId:string,graphRaw:unknown,note?:string){const graph=dialogGraphSchema.parse(graphRaw);return withTransaction(async client=>{const doc=await client.query(`SELECT current_draft_version FROM content_documents WHERE id=$1 FOR UPDATE`,[documentId]);if(!doc.rows[0])throw new AppError('Документ не найден',404,'CONTENT_DOCUMENT_NOT_FOUND');const version=Number(doc.rows[0].current_draft_version)+1;await client.query(`INSERT INTO content_versions(document_id,version,graph,change_note,created_by) VALUES($1,$2,$3,$4,$5)`,[documentId,version,JSON.stringify(graph),note??null,adminId]);await client.query(`UPDATE content_documents SET current_draft_version=$2,status=CASE WHEN status='archived' THEN 'draft' ELSE status END,updated_by=$3,updated_at=NOW() WHERE id=$1`,[documentId,version,adminId]);return{version};});}
export async function publishVersion(adminId:string,documentId:string,version:number,testAudience:unknown={}){const found=await pool.query(`SELECT 1 FROM content_versions WHERE document_id=$1 AND version=$2`,[documentId,version]);if(!found.rowCount)throw new AppError('Версия не найдена',404,'CONTENT_VERSION_NOT_FOUND');await pool.query(`UPDATE content_documents SET status='published',published_version=$2,test_audience=$3,updated_by=$4,updated_at=NOW() WHERE id=$1`,[documentId,version,JSON.stringify(testAudience),adminId]);return{ok:true};}
export async function rollbackVersion(adminId:string,documentId:string,version:number){const versionRow=await pool.query(`SELECT graph FROM content_versions WHERE document_id=$1 AND version=$2`,[documentId,version]);if(!versionRow.rows[0])throw new AppError('Версия не найдена',404,'CONTENT_VERSION_NOT_FOUND');return saveDraft(adminId,documentId,versionRow.rows[0].graph,`Откат к версии ${version}`);}
export async function documentDetail(id:string){const [doc,versions]=await Promise.all([pool.query(`SELECT * FROM content_documents WHERE id=$1`,[id]),pool.query(`SELECT v.version,v.change_note,v.created_at,a.username author FROM content_versions v LEFT JOIN admins a ON a.id=v.created_by WHERE v.document_id=$1 ORDER BY v.version DESC`,[id])]);if(!doc.rows[0])throw new AppError('Документ не найден',404,'CONTENT_DOCUMENT_NOT_FOUND');return{document:doc.rows[0],versions:versions.rows};}
export async function versionGraph(id:string,version:number){const r=await pool.query(`SELECT graph FROM content_versions WHERE document_id=$1 AND version=$2`,[id,version]);if(!r.rows[0])throw new AppError('Версия не найдена',404,'CONTENT_VERSION_NOT_FOUND');return r.rows[0].graph;}
