import crypto from 'node:crypto';
import { pool } from '../db.js';
import { config } from '../config.js';
import { AppError } from '../errors.js';

function validateScreenshot(value:string|undefined){if(!value)return null;if(!/^data:image\/(png|jpeg|webp);base64,/i.test(value))throw new AppError('Поддерживаются PNG, JPEG и WebP',400,'SCREENSHOT_FORMAT_INVALID');const bytes=Math.floor((value.split(',')[1]?.length??0)*.75);if(bytes>config.SUPPORT_SCREENSHOT_MAX_BYTES)throw new AppError('Скриншот слишком большой',413,'SCREENSHOT_TOO_LARGE');return value;}
export async function createTicket(userId:string|number,input:{category:string;subject:string;body:string;screenshot?:string;appVersion?:string;context?:Record<string,unknown>}){
  const id=crypto.randomUUID();const messageId=crypto.randomUUID();const context=await enrichContext(userId,input.context??{});
  await pool.query('BEGIN');try{await pool.query(`INSERT INTO support_tickets(id,user_id,category,subject,app_version,context) VALUES($1,$2,$3,$4,$5,$6)`,[id,userId,input.category,input.subject,input.appVersion??config.APP_VERSION,JSON.stringify(context)]);await pool.query(`INSERT INTO support_messages(id,ticket_id,author_user_id,body,screenshot_data) VALUES($1,$2,$3,$4,$5)`,[messageId,id,userId,input.body,validateScreenshot(input.screenshot)]);await pool.query('COMMIT');return{id};}catch(e){await pool.query('ROLLBACK');throw e;}
}
async function enrichContext(userId:string|number,extra:Record<string,unknown>){const [exp,purchase]=await Promise.all([pool.query(`SELECT id,status,room_index,started_at FROM expeditions WHERE user_id=$1 ORDER BY started_at DESC LIMIT 1`,[userId]),pool.query(`SELECT id,sku,stars,status,created_at FROM purchases WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1`,[userId])]);return{...extra,lastExpedition:exp.rows[0]??null,lastPurchase:purchase.rows[0]??null};}
export async function addUserMessage(userId:string|number,ticketId:string,body:string,screenshot?:string){const ticket=await pool.query(`SELECT status FROM support_tickets WHERE id=$1 AND user_id=$2`,[ticketId,userId]);if(!ticket.rowCount)throw new AppError('Обращение не найдено',404,'TICKET_NOT_FOUND');if(ticket.rows[0].status==='closed')throw new AppError('Обращение закрыто',409,'TICKET_CLOSED');await pool.query(`INSERT INTO support_messages(id,ticket_id,author_user_id,body,screenshot_data) VALUES($1,$2,$3,$4,$5)`,[crypto.randomUUID(),ticketId,userId,body,validateScreenshot(screenshot)]);await pool.query(`UPDATE support_tickets SET status='waiting_staff',updated_at=NOW() WHERE id=$1`,[ticketId]);return{ok:true};}
export async function userTickets(userId:string|number){const tickets=await pool.query(`SELECT * FROM support_tickets WHERE user_id=$1 ORDER BY updated_at DESC`,[userId]);const messages=await pool.query(`SELECT m.id,m.ticket_id,m.body,m.screenshot_data,m.created_at,m.author_user_id IS NOT NULL from_user,a.username admin_name FROM support_messages m LEFT JOIN admins a ON a.id=m.author_admin_id JOIN support_tickets t ON t.id=m.ticket_id WHERE t.user_id=$1 ORDER BY m.created_at`,[userId]);return{tickets:tickets.rows,messages:messages.rows};}
