import crypto from 'node:crypto';
import type { Server as HttpServer } from 'node:http';
import type { FastifyBaseLogger } from 'fastify';
import { Server, type Socket } from 'socket.io';
import { createAdapter } from '@socket.io/redis-streams-adapter';
import { config } from '../config.js';
import { requireRedis, withRedisLock } from '../redis.js';
import { authenticateInitDataString, assertNotBanned, upsertUser, type TelegramUser } from '../auth.js';
import { pool, withTransaction } from '../db.js';
import { loadEnabledRooms } from '../game/content.js';
import type { RoomTemplate } from '../game/catalog.js';
import { realtimeConnections, realtimeMatches } from '../observability/metrics.js';
import { ensureBuildingMembership } from '../services/building.js';
import { changeInventory } from '../services/economy.js';
import { recordBehavior } from '../services/storylines.js';
import { assertActionLimit } from '../security/anti-abuse.js';
import { relationshipEvent } from '../services/v4.js';

interface CoopPlayer{userId:string;name:string;username?:string;ready:boolean;connected:boolean;joinedAt:string;role?:string;privateHint:string;secretObjective:string;vote?:number;contribution:number;lastSeen:string;}
interface CoopShared{nerve:number;danger:number;noise:number;clues:number;keys:number;bag:Record<string,number>;lightsUsed:number;actions:Record<string,string[]>;}
interface CoopSpectator{userId:string;name:string;connected:boolean;usedIntervention:boolean;joinedAt:string;}
interface CoopScenario{contentKey:string;entitlementKey:string;title:string;guestSlots:number;roomThemes:string[];}
interface CoopState{id:string;code:string;hostId:string;buildingId:string;phase:'lobby'|'playing'|'escaped'|'lost'|'cancelled';maxPlayers:number;scenarioSku?:string;scenarioTitle?:string;scenario?:CoopScenario;players:Record<string,CoopPlayer>;spectators:Record<string,CoopSpectator>;rooms:RoomTemplate[];roomIndex:number;shared:CoopShared;votes:Record<string,number>;turnDeadlineAt:number|null;elevatorDeadlineAt:number|null;log:string[];version:number;createdAt:string;updatedAt:string;}
type Ack=(response:{ok:boolean;data?:unknown;error?:string;code?:string})=>void;
const hints=['На стене царапины складываются в номер квартиры.','Шаги повторяются с задержкой в три секунды.','Лампа гаснет перед безопасным выбором.','На обратной стороне таблички есть свежая дата.'];
const objectives=['Вернуться, сохранив хотя бы один ключ.','Ни разу не голосовать первым.','Помочь другому жильцу минимум дважды.','Найти две улики и никому не сообщать источник.','Не включать свет до возвращения.'];
function atOr<T>(items:T[],index:number,fallback:T):T{return items[index]??fallback;}
function randomFrom<T>(items:T[],fallback:T):T{return items.length?items[crypto.randomInt(items.length)]??fallback:fallback;}
function key(id:string){return`coop:match:${id}`;}function codeKey(code:string){return`coop:code:${code.toUpperCase()}`;}
function randomCode(){return crypto.randomBytes(5).toString('base64url').replace(/[-_]/g,'').slice(0,6).toUpperCase();}
function publicState(state:CoopState,userId:string){const player=state.players[userId];const spectator=state.spectators?.[userId];return{...state,rooms:state.phase==='playing'?[state.rooms[state.roomIndex]]:[],players:Object.values(state.players).map(({privateHint,secretObjective,...p})=>p),spectators:Object.values(state.spectators??{}),private:{hint:player?.privateHint,objective:player?.secretObjective},viewerMode:player?'player':spectator?'spectator':'none',roomsTotal:state.rooms.length,serverTime:Date.now()};}
async function saveState(state:CoopState){const redis=await requireRedis();state.version++;state.updatedAt=new Date().toISOString();await redis.set(key(state.id),JSON.stringify(state),{EX:config.COOP_MATCH_TTL_SECONDS});await redis.set(codeKey(state.code),state.id,{EX:config.COOP_MATCH_TTL_SECONDS});if(['lobby','playing'].includes(state.phase))await redis.sAdd('coop:active',state.id);else await redis.sRem('coop:active',state.id);await pool.query(`UPDATE coop_matches SET status=$2,snapshot=$3,started_at=CASE WHEN $2='playing' THEN COALESCE(started_at,NOW()) ELSE started_at END,completed_at=CASE WHEN $2 IN ('escaped','lost','cancelled') THEN COALESCE(completed_at,NOW()) ELSE completed_at END,updated_at=NOW() WHERE id=$1`,[state.id,state.phase,JSON.stringify(state)]);}
async function loadState(id:string):Promise<CoopState|null>{const redis=await requireRedis();const cached=await redis.get(key(id));if(cached){const state=JSON.parse(cached) as CoopState;state.spectators??={};return state;}const db=await pool.query(`SELECT snapshot FROM coop_matches WHERE id=$1 AND status IN ('lobby','playing')`,[id]);if(!db.rows[0])return null;const state=db.rows[0].snapshot as CoopState;state.spectators??={};await redis.set(key(id),JSON.stringify(state),{EX:config.COOP_MATCH_TTL_SECONDS});return state;}
async function stateByCode(code:string){const redis=await requireRedis();const id=await redis.get(codeKey(code));if(id)return loadState(id);const db=await pool.query(`SELECT id FROM coop_matches WHERE code=$1 AND status IN ('lobby','playing')`,[code.toUpperCase()]);return db.rows[0]?loadState(db.rows[0].id):null;}
async function socketUser(socket:Socket):Promise<TelegramUser>{const initData=socket.handshake.auth?.initData;if(typeof initData==='string'&&initData)return authenticateInitDataString(initData);if(config.ALLOW_DEV_AUTH&&config.NODE_ENV!=='production'){const id=Number(socket.handshake.auth?.devUserId||config.DEV_USER_ID);const user={id,first_name:`Тестовый жилец ${id}`,username:`resident_${id}`};await upsertUser(user);await assertNotBanned(id);return user;}throw new Error('Откройте кооператив из Telegram');}
async function emitState(io:Server,state:CoopState){for(const player of Object.values(state.players))io.to(`user:${player.userId}`).emit('coop:state',publicState(state,player.userId));for(const spectator of Object.values(state.spectators??{}))io.to(`user:${spectator.userId}`).emit('coop:state',publicState(state,spectator.userId));realtimeMatches.set({phase:state.phase},['lobby','playing'].includes(state.phase)?1:0);}
async function scenarioDefinition(userId:number,rawScenario?:string):Promise<CoopScenario|undefined>{
  if(!rawScenario)return undefined;
  const normalized=String(rawScenario).trim().replace(/^coop:/,'coop-').replace(/_/g,'-');
  const inventory=await pool.query(`SELECT content_key,title,metadata FROM content_inventory WHERE content_type='coop_case' AND active=TRUE AND (content_key=$1 OR regexp_replace(content_key,'^coop-','')=$2) LIMIT 1`,[normalized,normalized.replace(/^coop-/,'')]);
  const row=inventory.rows[0];if(!row)throw new Error('Кооперативное дело не найдено');
  const slug=String(row.content_key).replace(/^coop-/,'');
  const entitlementKey=`coop:${slug}`;
  const owned=await pool.query(`SELECT value FROM entitlements WHERE user_id=$1 AND entitlement_key=$2`,[userId,entitlementKey]);
  if(!owned.rowCount)throw new Error('Это дело должен открыть владелец сюжетного билета');
  const metadata=row.metadata??{};const value=owned.rows[0]?.value??{};
  const guestSlots=Math.max(1,Math.min(3,Number(value.guestSlots??metadata.guestSlots??2)));
  return{contentKey:row.content_key,entitlementKey,title:row.title,guestSlots,roomThemes:Array.isArray(metadata.rooms)?metadata.rooms.map(String):[]};
}
async function roomsForScenario(scenario?:CoopScenario):Promise<RoomTemplate[]>{
  const enabled=await loadEnabledRooms();if(!scenario?.roomThemes.length)return enabled.sort(()=>Math.random()-.5).slice(0,6);
  const selected:RoomTemplate[]=[];
  for(const theme of scenario.roomThemes){
    const matches=enabled.filter(room=>room.id===theme||room.id.includes(theme)||room.ambience===theme);
    for(const room of matches.sort(()=>Math.random()-.5).slice(0,2))if(!selected.some(item=>item.id===room.id))selected.push(room);
  }
  for(const room of enabled.sort(()=>Math.random()-.5))if(selected.length<6&&!selected.some(item=>item.id===room.id))selected.push(room);
  return selected.slice(0,6);
}
async function createMatch(user:TelegramUser,maxPlayers=4,scenarioSku?:string){const scenario=await scenarioDefinition(user.id,scenarioSku);if(scenario)maxPlayers=Math.min(maxPlayers,1+scenario.guestSlots);const buildingId=await ensureBuildingMembership(user.id);const id=crypto.randomUUID();let code=randomCode();while((await pool.query(`SELECT 1 FROM coop_matches WHERE code=$1`,[code])).rowCount)code=randomCode();const role=await pool.query(`SELECT role_key FROM role_progress WHERE user_id=$1`,[user.id]);const now=new Date().toISOString();const state:CoopState={id,code,hostId:String(user.id),buildingId,phase:'lobby',maxPlayers,scenarioSku:scenario?.contentKey??scenarioSku,scenarioTitle:scenario?.title,scenario,players:{[String(user.id)]:{userId:String(user.id),name:user.first_name,username:user.username,ready:false,connected:true,joinedAt:now,role:role.rows[0]?.role_key,privateHint:atOr(hints,0,'Слушай шаги.'),secretObjective:randomFrom(objectives,'Вернуться к лифту.'),contribution:0,lastSeen:now}},spectators:{},rooms:[],roomIndex:0,shared:{nerve:100,danger:0,noise:0,clues:0,keys:1,bag:{},lightsUsed:0,actions:{}},votes:{},turnDeadlineAt:null,elevatorDeadlineAt:null,log:['Лифт ждёт остальных жильцов.'],version:0,createdAt:now,updatedAt:now};await pool.query(`INSERT INTO coop_matches(id,code,host_id,building_id,status,snapshot,max_players,scenario_sku) VALUES($1,$2,$3,$4,'lobby',$5,$6,$7)`,[id,code,user.id,buildingId,JSON.stringify(state),maxPlayers,scenarioSku??null]);await pool.query(`INSERT INTO coop_members(match_id,user_id,secret_objective,private_hint) VALUES($1,$2,$3,$4)`,[id,user.id,state.players[String(user.id)]!.secretObjective,state.players[String(user.id)]!.privateHint]);await saveState(state);return state;}
async function joinMatch(state:CoopState,user:TelegramUser){if(!['lobby','playing'].includes(state.phase))throw new Error('Эта вылазка уже завершена');const id=String(user.id);if(!state.players[id]){if(Object.keys(state.players).length>=state.maxPlayers)throw new Error('В лифте больше нет места');if(state.phase!=='lobby')throw new Error('После начала новые жильцы не допускаются');const role=await pool.query(`SELECT role_key FROM role_progress WHERE user_id=$1`,[id]);const index=Object.keys(state.players).length;state.players[id]={userId:id,name:user.first_name,username:user.username,ready:false,connected:true,joinedAt:new Date().toISOString(),role:role.rows[0]?.role_key,privateHint:atOr(hints,index%Math.max(hints.length,1),'Слушай шаги.'),secretObjective:randomFrom(objectives,'Вернуться к лифту.'),contribution:0,lastSeen:new Date().toISOString()};await pool.query(`INSERT INTO coop_members(match_id,user_id,secret_objective,private_hint) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[state.id,id,state.players[id].secretObjective,state.players[id].privateHint]);}else{state.players[id].connected=true;state.players[id].lastSeen=new Date().toISOString();}await saveState(state);return state;}
function applyEffects(shared:CoopShared,effects:any){shared.nerve=Math.max(0,Math.min(100,shared.nerve+Number(effects.nerve??0)));shared.danger=Math.max(0,Math.min(100,shared.danger+Number(effects.danger??0)));shared.noise=Math.max(0,Math.min(100,shared.noise+Number(effects.noise??0)));shared.clues=Math.max(0,shared.clues+Number(effects.clues??0));shared.keys=Math.max(0,shared.keys+Number(effects.keys??0));if(effects.item)shared.bag[effects.item]=(shared.bag[effects.item]??0)+Number(effects.itemQty??1);}
async function resolveVote(state:CoopState,io:Server){if(state.phase!=='playing')return;const room=state.rooms[state.roomIndex];if(!room)return finishMatch(state,'escaped',io);const counts=new Map<number,number>();for(const vote of Object.values(state.votes))counts.set(vote,(counts.get(vote)??0)+1);let choiceIndex=0;let best=-1;for(const[index,count]of counts)if(count>best||(count===best&&index<choiceIndex)){choiceIndex=index;best=count;}const choice=room.choices[choiceIndex]??room.choices[0];if(!choice)return finishMatch(state,'escaped',io);applyEffects(state.shared,choice.effects);state.log.push(`${room.title}: ${choice.outcome}`);for(const p of Object.values(state.players))p.vote=undefined;state.votes={};state.roomIndex++;if(state.shared.danger>=100||state.shared.nerve<=0)return finishMatch(state,'lost',io);if(state.roomIndex>=state.rooms.length)return finishMatch(state,'escaped',io);state.turnDeadlineAt=Date.now()+config.COOP_TURN_SECONDS*1000;await saveState(state);await emitState(io,state);}
async function finishMatch(state:CoopState,result:'escaped'|'lost',io:Server){if(!['lobby','playing'].includes(state.phase))return;state.phase=result;state.turnDeadlineAt=null;state.elevatorDeadlineAt=null;state.log.push(result==='escaped'?'Лифт вернул группу домой.':'Двери лифта закрылись без группы.');await withTransaction(async client=>{const updated=await client.query(`UPDATE coop_matches SET status=$2,snapshot=$3,completed_at=NOW(),updated_at=NOW() WHERE id=$1 AND status IN ('lobby','playing') RETURNING id`,[state.id,result,JSON.stringify(state)]);if(!updated.rowCount)return;for(const player of Object.values(state.players)){const clueReward=result==='escaped'?state.shared.clues:Math.floor(state.shared.clues*.25);await client.query(`UPDATE player_profiles SET clues=clues+$2,trust=trust+$3,nerve=CASE WHEN $4='escaped' THEN 100 ELSE 55 END WHERE user_id=$1`,[player.userId,clueReward,result==='escaped'?3:0,result]);for(const[itemId,quantity]of Object.entries(state.shared.bag)){const keep=result==='escaped'?quantity:Math.floor(quantity*.25);if(keep>0)await changeInventory(client,player.userId,itemId,keep,'coop_reward',`coop:${state.id}:${player.userId}`,{result});}await client.query(`UPDATE coop_members SET contribution=$3 WHERE match_id=$1 AND user_id=$2`,[state.id,player.userId,player.contribution]);}});await saveState(state);await emitState(io,state);for(const player of Object.values(state.players))void recordBehavior(player.userId,result==='escaped'?'rescue':'abandon',1,{matchId:state.id}).catch(()=>undefined);}
async function matchmaking(user:TelegramUser,io:Server){const redis=await requireRedis();return withRedisLock('coop:matchmaking',5000,async()=>{await redis.zAdd('coop:queue',[{score:Date.now(),value:String(user.id)}]);await redis.hSet(`coop:queue:user:${user.id}`,{name:user.first_name,username:user.username??''});await redis.expire(`coop:queue:user:${user.id}`,300);const waiting=await redis.zRange('coop:queue',0,3);if(waiting.length<2)return{queued:true,position:await redis.zRank('coop:queue',String(user.id))};const profiles=[] as TelegramUser[];for(const id of waiting){const data=await redis.hGetAll(`coop:queue:user:${id}`);profiles.push({id:Number(id),first_name:data.name||`Жилец ${id}`,username:data.username||undefined});}const first=profiles[0];if(!first)return{queued:true,position:0};const match=await createMatch(first,4);for(const profile of profiles.slice(1))await joinMatch(match,profile);for(const id of waiting)await redis.zRem('coop:queue',id);await saveState(match);for(const p of Object.values(match.players))io.to(`user:${p.userId}`).emit('coop:matched',publicState(match,p.userId));return{queued:false,state:publicState(match,String(user.id))};})}

export async function createRealtimeServer(server:HttpServer,logger:FastifyBaseLogger){
  const redis=await requireRedis();const io=new Server(server,{path:'/socket.io',cors:{origin:false},connectionStateRecovery:{maxDisconnectionDuration:120_000,skipMiddlewares:false},pingInterval:20_000,pingTimeout:15_000,maxHttpBufferSize:100_000});io.adapter(createAdapter(redis,{maxLen:20_000,sessionKeyPrefix:'coop-session'}));
  io.use(async(socket,next)=>{try{const user=await socketUser(socket);socket.data.user=user;next();}catch(error){next(error instanceof Error?error:new Error('Авторизация не пройдена'));}});
  io.on('connection',socket=>{const user=socket.data.user as TelegramUser;const uid=String(user.id);socket.join(`user:${uid}`);realtimeConnections.inc();void redis.set(`presence:${uid}`,JSON.stringify({socketId:socket.id,at:Date.now()}),{EX:config.PRESENCE_TTL_SECONDS});
    const asAck=(value:unknown):Ack=>typeof value==='function'?(value as Ack):()=>{};
    const safe=(fn:(ack:Ack)=>Promise<void>)=>(...args:unknown[])=>{const ack=asAck(args.at(-1));void fn(ack).catch(error=>ack({ok:false,error:error instanceof Error?error.message:String(error),code:(error as any)?.code}));};
    socket.on('presence:heartbeat',safe(async ack=>{await redis.set(`presence:${uid}`,JSON.stringify({socketId:socket.id,at:Date.now()}),{EX:config.PRESENCE_TTL_SECONDS});ack({ok:true});}));
    socket.on('coop:create',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{await assertActionLimit(uid,'coop_create',5,3600);const state=await createMatch(user,Math.max(2,Math.min(4,Number(payload?.maxPlayers??4))),payload?.scenarioSku);await socket.join(`coop:${state.id}`);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:join',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=await stateByCode(String(payload?.code??''));if(!state)throw new Error('Комната с таким кодом не найдена');await joinMatch(state,user);await socket.join(`coop:${state.id}`);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:matchmake',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const result=await matchmaking(user,io);ack({ok:true,data:result});}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:resume',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=payload?.matchId?await loadState(String(payload.matchId)):payload?.code?await stateByCode(String(payload.code)):null;if(!state||!state.players[uid])throw new Error('Активная вылазка не найдена');state.players[uid].connected=true;state.players[uid].lastSeen=new Date().toISOString();await saveState(state);await socket.join(`coop:${state.id}`);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:ready',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=await loadState(String(payload?.matchId));if(!state||!state.players[uid])throw new Error('Комната не найдена');state.players[uid].ready=Boolean(payload?.ready);await saveState(state);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:start',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=await loadState(String(payload?.matchId));if(!state||state.hostId!==uid)throw new Error('Только создатель может запустить лифт');if(Object.keys(state.players).length<2)throw new Error('Нужно минимум два жильца');if(Object.values(state.players).some(p=>!p.ready&&p.userId!==uid))throw new Error('Не все жильцы готовы');state.rooms=await roomsForScenario(state.scenario);state.phase='playing';state.roomIndex=0;state.turnDeadlineAt=Date.now()+config.COOP_TURN_SECONDS*1000;state.elevatorDeadlineAt=Date.now()+config.COOP_ELEVATOR_SECONDS*1000;state.log.push(state.scenarioTitle?`Дело «${state.scenarioTitle}» началось. Двери закрылись.`:'Двери закрылись. Лифт больше не отвечает кнопкам.');await saveState(state);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:action',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{await assertActionLimit(uid,'coop_action',30,60);const state=await loadState(String(payload?.matchId));if(!state||state.phase!=='playing'||!state.players[uid])throw new Error('Вылазка недоступна');const action=String(payload?.action??'');const roomKey=String(state.roomIndex);state.shared.actions[roomKey]??=[];const marker=`${uid}:${action}`;if(state.shared.actions[roomKey].includes(marker))throw new Error('Это действие уже выполнено');state.shared.actions[roomKey].push(marker);if(action==='inspect'){state.shared.clues++;state.players[uid]!.privateHint=atOr(hints,(state.roomIndex+Number(uid.slice(-1)))%Math.max(hints.length,1),'Слушай шаги.');state.players[uid]!.contribution+=2;}else if(action==='help'){state.shared.nerve=Math.min(100,state.shared.nerve+5);state.players[uid]!.contribution+=3;const other=Object.values(state.players).find(p=>p.userId!==uid);if(other)void relationshipEvent(Number(uid),Number(other.userId),'help',{matchId:state.id}).catch(()=>undefined);}else if(action==='mark'){state.shared.danger=Math.max(0,state.shared.danger-5);state.players[uid]!.contribution++;}else if(action==='light'){state.shared.lightsUsed++;state.shared.danger=Math.max(0,state.shared.danger-8);state.shared.noise+=4;}else throw new Error('Неизвестное действие');state.log.push(`${state.players[uid]!.name}: ${action}`);await saveState(state);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:vote',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=await loadState(String(payload?.matchId));if(!state||state.phase!=='playing'||!state.players[uid])throw new Error('Вылазка недоступна');const choice=Number(payload?.choiceIndex);const room=state.rooms[state.roomIndex];if(!room)throw new Error('Комната не найдена');if(!Number.isInteger(choice)||choice<0||choice>=room.choices.length)throw new Error('Вариант решения недоступен');state.votes[uid]=choice;state.players[uid]!.vote=choice;await saveState(state);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);if(Object.keys(state.votes).length>=Object.keys(state.players).length)await resolveVote(state,io);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:spectate',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=payload?.matchId?await loadState(String(payload.matchId)):payload?.code?await stateByCode(String(payload.code)):null;if(!state||state.phase!=='playing')throw new Error('Наблюдать можно только активную вылазку');state.spectators??={};state.spectators[uid]={userId:uid,name:user.first_name,connected:true,usedIntervention:false,joinedAt:new Date().toISOString()};await socket.join(`coop:${state.id}`);await saveState(state);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:spectator-action',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=await loadState(String(payload?.matchId));const spectator=state?.spectators?.[uid];if(!state||state.phase!=='playing'||!spectator)throw new Error('Режим наблюдателя недоступен');if(spectator.usedIntervention)throw new Error('Вы уже вмешались в эту вылазку');const action=String(payload?.action||'');if(action==='light'){state.shared.danger=Math.max(0,state.shared.danger-7);state.log.push(`${spectator.name} включил аварийный свет через камеру.`);}else if(action==='mark'){state.shared.clues+=1;state.log.push(`${spectator.name} оставил отметку на плёнке.`);}else throw new Error('Неизвестное вмешательство');spectator.usedIntervention=true;await saveState(state);ack({ok:true,data:publicState(state,uid)});await emitState(io,state);}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('coop:leave',(payload:any,rawAck:unknown)=>{const ack=asAck(rawAck);void(async()=>{try{const state=await loadState(String(payload?.matchId));if(state?.players[uid]){state.players[uid].connected=false;state.players[uid].lastSeen=new Date().toISOString();await pool.query(`UPDATE coop_members SET left_at=NOW() WHERE match_id=$1 AND user_id=$2`,[state.id,uid]);if(state.phase==='lobby'&&state.hostId===uid){const next=Object.values(state.players).find(p=>p.userId!==uid);if(next)state.hostId=next.userId;else state.phase='cancelled';}await saveState(state);await emitState(io,state);}ack({ok:true});}catch(e){ack({ok:false,error:e instanceof Error?e.message:String(e)});}})();});
    socket.on('disconnect',()=>{realtimeConnections.dec();void redis.del(`presence:${uid}`);void (async()=>{const active=await pool.query(`SELECT id FROM coop_matches WHERE status IN ('lobby','playing') AND EXISTS(SELECT 1 FROM coop_members WHERE match_id=coop_matches.id AND user_id=$1 AND left_at IS NULL) ORDER BY updated_at DESC LIMIT 1`,[uid]);if(active.rows[0]){const state=await loadState(active.rows[0].id);if(state?.players[uid]){state.players[uid].connected=false;state.players[uid].lastSeen=new Date().toISOString();await saveState(state);await emitState(io,state);}}})().catch(()=>undefined);});
  });
  const timer=setInterval(()=>void(async()=>{const ids=await redis.sMembers('coop:active');for(const id of ids){await withRedisLock(`coop-tick:${id}`,1500,async()=>{const state=await loadState(id);if(!state)return;if(state.phase==='playing'&&state.elevatorDeadlineAt&&Date.now()>=state.elevatorDeadlineAt)return finishMatch(state,'lost',io);if(state.phase==='playing'&&state.turnDeadlineAt&&Date.now()>=state.turnDeadlineAt)return resolveVote(state,io);if(state.phase==='lobby'&&Date.now()-new Date(state.createdAt).getTime()>config.COOP_MATCH_TTL_SECONDS*1000){state.phase='cancelled';await saveState(state);await emitState(io,state);}});}})().catch(error=>logger.error({error},'Coop timer failed')),1000);timer.unref();logger.info('Socket.IO cooperative service started');return{io,stop:()=>{clearInterval(timer);io.close();}};
}
