import { config } from '../config.js';
import { pool } from '../db.js';
import { sendBotMessage } from '../telegram.js';
import { getRedis,withRedisLock } from '../redis.js';
import { queueDepth } from '../observability/metrics.js';

let running=false;let timer:NodeJS.Timeout|null=null;
async function nextDeliveries(broadcastId:string):Promise<string[]>{const redis=await getRedis();if(!redis){return(await pool.query(`SELECT user_id::text FROM broadcast_deliveries WHERE broadcast_id=$1 AND status='pending' ORDER BY user_id LIMIT $2`,[broadcastId,config.BROADCAST_BATCH_SIZE])).rows.map(x=>x.user_id);}const queue=`queue:broadcast:${broadcastId}`;const initialized=`${queue}:initialized`;if(!await redis.exists(initialized)){await withRedisLock(`broadcast-init:${broadcastId}`,30_000,async()=>{if(await redis.exists(initialized))return;const rows=await pool.query(`SELECT user_id::text FROM broadcast_deliveries WHERE broadcast_id=$1 AND status='pending' ORDER BY user_id`,[broadcastId]);if(rows.rowCount)await redis.rPush(queue,rows.rows.map(x=>x.user_id));await redis.set(initialized,'1',{EX:7*86400});});}const items=[] as string[];for(let i=0;i<config.BROADCAST_BATCH_SIZE;i++){const id=await redis.lPop(queue);if(!id)break;items.push(id);}queueDepth.set({queue:'broadcast'},await redis.lLen(queue));return items;}
async function processBroadcasts():Promise<void>{if(running)return;running=true;try{const campaign=await pool.query(`SELECT id,title,body,button_text,button_url FROM broadcasts WHERE status IN ('queued','running') ORDER BY created_at LIMIT 1`);const item=campaign.rows[0];if(!item)return;await pool.query(`UPDATE broadcasts SET status='running' WHERE id=$1 AND status='queued'`,[item.id]);const deliveries=await nextDeliveries(item.id);if(!deliveries.length){const pending=await pool.query(`SELECT COUNT(*)::int count FROM broadcast_deliveries WHERE broadcast_id=$1 AND status='pending'`,[item.id]);if(Number(pending.rows[0].count)===0)await pool.query(`UPDATE broadcasts SET status='completed',completed_at=NOW() WHERE id=$1 AND status='running'`,[item.id]);return;}for(const userId of deliveries){const current=await pool.query(`SELECT status FROM broadcasts WHERE id=$1`,[item.id]);if(current.rows[0]?.status!=='running')break;try{await sendBotMessage(userId,item.body,item.button_text,item.button_url);const changed=await pool.query(`UPDATE broadcast_deliveries SET status='sent',sent_at=NOW(),error=NULL WHERE broadcast_id=$1 AND user_id=$2 AND status='pending' RETURNING user_id`,[item.id,userId]);if(changed.rowCount)await pool.query(`UPDATE broadcasts SET sent=sent+1 WHERE id=$1`,[item.id]);}catch(error){const message=error instanceof Error?error.message:String(error);const changed=await pool.query(`UPDATE broadcast_deliveries SET status='failed',error=$3 WHERE broadcast_id=$1 AND user_id=$2 AND status='pending' RETURNING user_id`,[item.id,userId,message.slice(0,500)]);if(changed.rowCount)await pool.query(`UPDATE broadcasts SET failed=failed+1 WHERE id=$1`,[item.id]);}await new Promise(r=>setTimeout(r,70));}}finally{running=false;}}
export function startBroadcastWorker(log:{error:(value:unknown,message?:string)=>void}):()=>void{timer=setInterval(()=>void processBroadcasts().catch(error=>log.error({error},'Broadcast worker failed')),1200);timer.unref();return()=>{if(timer)clearInterval(timer);timer=null;};}
