import crypto from 'node:crypto';
import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import { pool,withTransaction } from '../db.js';
import { config } from '../config.js';
import { AppError } from '../errors.js';
import { productAnalytics } from '../services/analytics.js';
import { createBackup } from '../backup/worker.js';
import { createDocument,dialogGraphSchema,documentDetail,listDocuments,publishVersion,rollbackVersion,saveDraft,versionGraph } from '../services/content-versioning.js';
import { writeAudit } from './audit.js';
import { hasPermission,type AdminPrincipal,type Permission } from './rbac.js';
import { sendBotMessage } from '../telegram.js';
import { changeInventory,changeMarks } from '../services/economy.js';
import { getRedis,redisHealth } from '../redis.js';
import { registry } from '../observability/metrics.js';

function adminOf(request:FastifyRequest):AdminPrincipal{return(request as any).adminPrincipal;}
function requirePermission(request:FastifyRequest,p:Permission){const a=adminOf(request);if(!hasPermission(a,p))throw new AppError('Недостаточно прав',403,'ADMIN_PERMISSION_DENIED');return a;}
const uuid=z.string().uuid();
export async function adminV2Routes(app:FastifyInstance){
  app.get('/admin/api/v2/analytics',async request=>{requirePermission(request,'analytics:read');const q=z.object({days:z.coerce.number().int().min(7).max(180).default(30)}).parse(request.query);const base=await productAnalytics(q.days);const [rooms,products,versions,errors]=await Promise.all([
    pool.query(`SELECT properties->>'roomId' room_id,COUNT(*)::int choices,COUNT(DISTINCT user_id)::int users FROM analytics_events WHERE event_name='room_choice' AND created_at>=CURRENT_DATE-$1::int GROUP BY room_id ORDER BY choices DESC`,[q.days]),
    pool.query(`SELECT p.sku,s.title,COUNT(*)::int purchases,SUM(p.stars)::int stars,COUNT(DISTINCT p.user_id)::int payers FROM purchases p LEFT JOIN shop_products s ON s.sku=p.sku WHERE p.status='paid' AND p.created_at>=CURRENT_DATE-$1::int GROUP BY p.sku,s.title ORDER BY stars DESC`,[q.days]),
    pool.query(`SELECT app_version,COUNT(*)::int events,COUNT(*) FILTER(WHERE event_name='client_error')::int errors FROM analytics_events WHERE created_at>=CURRENT_DATE-$1::int GROUP BY app_version ORDER BY events DESC`,[q.days]),
    pool.query(`SELECT properties->>'message' message,COUNT(*)::int count FROM analytics_events WHERE event_name='client_error' AND created_at>=CURRENT_DATE-$1::int GROUP BY message ORDER BY count DESC LIMIT 30`,[q.days])
  ]);return{...base,rooms:rooms.rows,products:products.rows,versions:versions.rows,errors:errors.rows};});

  app.get('/admin/api/v2/daily-scenarios',async request=>{requirePermission(request,'content:read');return{items:(await pool.query(`SELECT * FROM daily_scenarios ORDER BY scheduled_date DESC NULLS LAST,weekday,priority DESC`)).rows};});
  app.post('/admin/api/v2/daily-scenarios',async request=>{const admin=requirePermission(request,'content:write');const b=z.object({slug:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(2).max(120),teaser:z.string().min(5).max(500),scenes:z.array(z.any()).min(2).max(30),rewardConfig:z.record(z.unknown()).default({}),active:z.boolean().default(true),scheduledDate:z.string().date().optional().nullable(),weekday:z.number().int().min(0).max(6).optional().nullable(),priority:z.number().int().min(0).max(1000).default(0)}).parse(request.body);const id=crypto.randomUUID();await pool.query(`INSERT INTO daily_scenarios(id,slug,title,teaser,scenes,reward_config,active,scheduled_date,weekday,priority,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[id,b.slug,b.title,b.teaser,JSON.stringify(b.scenes),JSON.stringify(b.rewardConfig),b.active,b.scheduledDate??null,b.weekday??null,b.priority,admin.id]);await writeAudit(admin,'daily.create','daily_scenario',id,b,request);return{id};});
  app.patch('/admin/api/v2/daily-scenarios/:id',async request=>{const admin=requirePermission(request,'content:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({title:z.string().min(2).max(120).optional(),teaser:z.string().min(5).max(500).optional(),scenes:z.array(z.any()).min(2).max(30).optional(),rewardConfig:z.record(z.unknown()).optional(),active:z.boolean().optional(),scheduledDate:z.string().date().optional().nullable(),weekday:z.number().int().min(0).max(6).optional().nullable(),priority:z.number().int().min(0).max(1000).optional()}).parse(request.body);await pool.query(`UPDATE daily_scenarios SET title=COALESCE($2,title),teaser=COALESCE($3,teaser),scenes=COALESCE($4,scenes),reward_config=COALESCE($5,reward_config),active=COALESCE($6,active),scheduled_date=CASE WHEN $7::boolean THEN $8::date ELSE scheduled_date END,weekday=CASE WHEN $9::boolean THEN $10::int ELSE weekday END,priority=COALESCE($11,priority),updated_at=NOW() WHERE id=$1`,[id,b.title??null,b.teaser??null,b.scenes?JSON.stringify(b.scenes):null,b.rewardConfig?JSON.stringify(b.rewardConfig):null,b.active??null,Object.prototype.hasOwnProperty.call(b,'scheduledDate'),b.scheduledDate??null,Object.prototype.hasOwnProperty.call(b,'weekday'),b.weekday??null,b.priority??null]);await writeAudit(admin,'daily.update','daily_scenario',id,b,request);return{ok:true};});
  app.delete('/admin/api/v2/daily-scenarios/:id',async request=>{const admin=requirePermission(request,'content:write');const{id}=z.object({id:uuid}).parse(request.params);await pool.query(`DELETE FROM daily_scenarios WHERE id=$1`,[id]);await writeAudit(admin,'daily.delete','daily_scenario',id,{},request);return{ok:true};});

  app.get('/admin/api/v2/buildings',async request=>{requirePermission(request,'operations:read');const rows=await pool.query(`SELECT b.*,u.first_name elder_name,(SELECT COUNT(*) FROM building_members m WHERE m.building_id=b.id)::int members,(SELECT COUNT(*) FROM building_posts p WHERE p.building_id=b.id AND p.hidden=FALSE)::int posts FROM buildings b LEFT JOIN users u ON u.id=b.elder_user_id ORDER BY b.code`);return{items:rows.rows};});
  app.get('/admin/api/v2/buildings/:id',async request=>{requirePermission(request,'operations:read');const{id}=z.object({id:uuid}).parse(request.params);const[building,members,storage,posts,votes,goals]=await Promise.all([pool.query(`SELECT * FROM buildings WHERE id=$1`,[id]),pool.query(`SELECT m.*,u.id::text,u.first_name,u.username,p.apartment_no,p.profession FROM building_members m JOIN users u ON u.id=m.user_id JOIN player_profiles p ON p.user_id=u.id WHERE m.building_id=$1 ORDER BY m.local_trust DESC`,[id]),pool.query(`SELECT * FROM building_storage WHERE building_id=$1 ORDER BY item_id`,[id]),pool.query(`SELECT p.*,u.first_name author_name FROM building_posts p JOIN users u ON u.id=p.author_id WHERE p.building_id=$1 ORDER BY p.created_at DESC LIMIT 100`,[id]),pool.query(`SELECT * FROM building_votes WHERE building_id=$1 ORDER BY created_at DESC LIMIT 50`,[id]),pool.query(`SELECT * FROM building_weekly_goals WHERE building_id=$1 ORDER BY week_start DESC`,[id])]);return{building:building.rows[0],members:members.rows,storage:storage.rows,posts:posts.rows,votes:votes.rows,goals:goals.rows};});
  app.patch('/admin/api/v2/buildings/:id',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({title:z.string().min(2).max(120).optional(),elderUserId:z.string().regex(/^\d+$/).optional().nullable(),trustScore:z.number().int().min(-10000).max(10000).optional(),sharedProgress:z.number().int().min(0).max(1000000).optional(),consequences:z.array(z.unknown()).optional()}).parse(request.body);await pool.query(`UPDATE buildings SET title=COALESCE($2,title),elder_user_id=CASE WHEN $3::boolean THEN $4::bigint ELSE elder_user_id END,trust_score=COALESCE($5,trust_score),shared_progress=COALESCE($6,shared_progress),consequences=COALESCE($7,consequences),updated_at=NOW() WHERE id=$1`,[id,b.title??null,Object.prototype.hasOwnProperty.call(b,'elderUserId'),b.elderUserId??null,b.trustScore??null,b.sharedProgress??null,b.consequences?JSON.stringify(b.consequences):null]);await writeAudit(admin,'building.update','building',id,b,request);return{ok:true};});
  app.patch('/admin/api/v2/building-posts/:id',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({hidden:z.boolean().optional(),pinned:z.boolean().optional()}).parse(request.body);await pool.query(`UPDATE building_posts SET hidden=COALESCE($2,hidden),pinned=COALESCE($3,pinned) WHERE id=$1`,[id,b.hidden??null,b.pinned??null]);await writeAudit(admin,'building.post.update','building_post',id,b,request);return{ok:true};});

  app.get('/admin/api/v2/market',async request=>{requirePermission(request,'operations:read');const[listings,trades,orders]=await Promise.all([pool.query(`SELECT l.*,u.first_name seller_name,u.username seller_username FROM market_listings l JOIN users u ON u.id=l.seller_id ORDER BY l.created_at DESC LIMIT 300`),pool.query(`SELECT t.*,s.first_name seller_name,b.first_name buyer_name FROM market_trades t LEFT JOIN users s ON s.id=t.seller_id LEFT JOIN users b ON b.id=t.buyer_id ORDER BY t.created_at DESC LIMIT 300`),pool.query(`SELECT o.*,u.first_name buyer_name FROM market_orders o JOIN users u ON u.id=o.buyer_id ORDER BY o.created_at DESC LIMIT 200`)]);return{listings:listings.rows,trades:trades.rows,orders:orders.rows};});
  app.post('/admin/api/v2/market/listings/:id/cancel',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);await withTransaction(async client=>{const r=await client.query(`SELECT * FROM market_listings WHERE id=$1 FOR UPDATE`,[id]);const row=r.rows[0];if(!row||row.status!=='active')return;if(Number(row.remaining)>0)await changeInventory(client,row.seller_id,row.item_id,Number(row.remaining),'admin_market_cancel',`admin-market:${id}`);await client.query(`UPDATE market_listings SET status='cancelled',remaining=0,updated_at=NOW() WHERE id=$1`,[id]);});await writeAudit(admin,'market.cancel','market_listing',id,{},request);return{ok:true};});

  app.get('/admin/api/v2/support',async request=>{requirePermission(request,'operations:read');const q=z.object({status:z.string().default('all'),search:z.string().max(100).default('')}).parse(request.query);const rows=await pool.query(`SELECT t.*,u.first_name,u.username,(SELECT COUNT(*) FROM support_messages m WHERE m.ticket_id=t.id)::int messages FROM support_tickets t JOIN users u ON u.id=t.user_id WHERE ($1='all' OR t.status=$1) AND ($2='' OR t.subject ILIKE '%'||$2||'%' OR u.first_name ILIKE '%'||$2||'%' OR u.username ILIKE '%'||$2||'%') ORDER BY CASE t.priority WHEN 'urgent' THEN 4 WHEN 'high' THEN 3 WHEN 'normal' THEN 2 ELSE 1 END DESC,t.updated_at DESC LIMIT 300`,[q.status,q.search]);return{items:rows.rows};});
  app.get('/admin/api/v2/support/:id',async request=>{requirePermission(request,'operations:read');const{id}=z.object({id:uuid}).parse(request.params);const[ticket,messages]=await Promise.all([pool.query(`SELECT t.*,u.first_name,u.username,u.id::text user_id FROM support_tickets t JOIN users u ON u.id=t.user_id WHERE t.id=$1`,[id]),pool.query(`SELECT m.*,u.first_name user_name,a.username admin_name FROM support_messages m LEFT JOIN users u ON u.id=m.author_user_id LEFT JOIN admins a ON a.id=m.author_admin_id WHERE m.ticket_id=$1 ORDER BY m.created_at`,[id])]);if(!ticket.rows[0])throw new AppError('Обращение не найдено',404,'TICKET_NOT_FOUND');return{ticket:ticket.rows[0],messages:messages.rows};});
  app.post('/admin/api/v2/support/:id/reply',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({body:z.string().min(1).max(3000),status:z.enum(['waiting_user','resolved','closed']).default('waiting_user'),sendTelegram:z.boolean().default(true)}).parse(request.body);const ticket=await pool.query(`SELECT user_id::text FROM support_tickets WHERE id=$1`,[id]);if(!ticket.rows[0])throw new AppError('Обращение не найдено',404,'TICKET_NOT_FOUND');await pool.query(`INSERT INTO support_messages(id,ticket_id,author_admin_id,body) VALUES($1,$2,$3,$4)`,[crypto.randomUUID(),id,admin.id,b.body]);await pool.query(`UPDATE support_tickets SET status=$2,updated_at=NOW() WHERE id=$1`,[id,b.status]);if(b.sendTelegram)await sendBotMessage(ticket.rows[0].user_id,`Ответ поддержки по обращению ${id.slice(0,8)}:\n\n${b.body}`,config.PUBLIC_URL?'Открыть игру':null,config.PUBLIC_URL??null).catch(()=>undefined);await writeAudit(admin,'support.reply','support_ticket',id,{status:b.status},request);return{ok:true};});

  app.get('/admin/api/v2/moderation',async request=>{requirePermission(request,'operations:read');const[reports,flags,actions,terms]=await Promise.all([pool.query(`SELECT r.*,a.first_name reporter_name,t.first_name target_name FROM user_reports r JOIN users a ON a.id=r.reporter_id JOIN users t ON t.id=r.target_user_id ORDER BY r.created_at DESC LIMIT 300`),pool.query(`SELECT f.*,u.first_name,u.username FROM risk_flags f JOIN users u ON u.id=f.user_id ORDER BY f.status='open' DESC,f.score DESC,f.created_at DESC LIMIT 500`),pool.query(`SELECT a.*,u.first_name,ad.username admin_name FROM moderation_actions a JOIN users u ON u.id=a.user_id LEFT JOIN admins ad ON ad.id=a.admin_id ORDER BY a.created_at DESC LIMIT 300`),pool.query(`SELECT * FROM moderation_terms ORDER BY severity DESC,pattern`)]);return{reports:reports.rows,flags:flags.rows,actions:actions.rows,terms:terms.rows};});
  app.post('/admin/api/v2/moderation/users/:id/action',async request=>{const admin=requirePermission(request,'users:moderate');const{id}=z.object({id:z.string().regex(/^\d+$/)}).parse(request.params);const b=z.object({action:z.enum(['mute','shadow_mute','ban','unmute','unban','warn']),reason:z.string().min(3).max(500),hours:z.number().int().min(1).max(8760).optional()}).parse(request.body);const expires=b.hours?new Date(Date.now()+b.hours*3600000):null;await pool.query(`INSERT INTO user_moderation(user_id) VALUES($1) ON CONFLICT DO NOTHING`,[id]);if(b.action==='mute')await pool.query(`UPDATE user_moderation SET muted_until=$2,reason=$3,updated_at=NOW() WHERE user_id=$1`,[id,expires,b.reason]);if(b.action==='shadow_mute')await pool.query(`UPDATE user_moderation SET shadow_muted=TRUE,reason=$2,updated_at=NOW() WHERE user_id=$1`,[id,b.reason]);if(b.action==='ban')await pool.query(`UPDATE user_moderation SET banned=TRUE,banned_until=$2,reason=$3,banned_by=$4,updated_at=NOW() WHERE user_id=$1`,[id,expires,b.reason,admin.id]);if(b.action==='unmute')await pool.query(`UPDATE user_moderation SET muted_until=NULL,shadow_muted=FALSE,updated_at=NOW() WHERE user_id=$1`,[id]);if(b.action==='unban')await pool.query(`UPDATE user_moderation SET banned=FALSE,banned_until=NULL,reason=NULL,updated_at=NOW() WHERE user_id=$1`,[id]);await pool.query(`INSERT INTO moderation_actions(id,user_id,admin_id,action,reason,expires_at) VALUES($1,$2,$3,$4,$5,$6)`,[crypto.randomUUID(),id,admin.id,b.action,b.reason,expires]);await writeAudit(admin,'moderation.action','user',id,b,request);return{ok:true};});
  app.patch('/admin/api/v2/moderation/flags/:id',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({status:z.enum(['open','reviewing','cleared','confirmed'])}).parse(request.body);await pool.query(`UPDATE risk_flags SET status=$2,reviewed_at=CASE WHEN $2 IN ('cleared','confirmed') THEN NOW() ELSE reviewed_at END,reviewed_by=$3 WHERE id=$1`,[id,b.status,admin.id]);await writeAudit(admin,'risk.review','risk_flag',id,b,request);return{ok:true};});
  app.post('/admin/api/v2/moderation/terms',async request=>{const admin=requirePermission(request,'operations:write');const b=z.object({pattern:z.string().min(1).max(300),severity:z.number().int().min(1).max(10),action:z.enum(['review','hide','mute']).default('review')}).parse(request.body);const id=crypto.randomUUID();new RegExp(b.pattern,'iu');await pool.query(`INSERT INTO moderation_terms(id,pattern,severity,action) VALUES($1,$2,$3,$4)`,[id,b.pattern,b.severity,b.action]);await writeAudit(admin,'moderation.term.create','moderation_term',id,b,request);return{id};});

  app.get('/admin/api/v2/content-documents',async request=>{requirePermission(request,'content:read');return{items:await listDocuments()};});
  app.post('/admin/api/v2/content-documents',async request=>{const admin=requirePermission(request,'content:write');const b=z.object({slug:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(2).max(160),contentType:z.string().min(2).max(60),graph:dialogGraphSchema,changeNote:z.string().max(300).optional()}).parse(request.body);const result=await createDocument(admin.id,b);await writeAudit(admin,'content.document.create','content_document',result.id,{slug:b.slug},request);return result;});
  app.get('/admin/api/v2/content-documents/:id',async request=>{requirePermission(request,'content:read');const{id}=z.object({id:uuid}).parse(request.params);return documentDetail(id);});
  app.get('/admin/api/v2/content-documents/:id/versions/:version',async request=>{requirePermission(request,'content:read');const{id,version}=z.object({id:uuid,version:z.coerce.number().int().positive()}).parse(request.params);return{graph:await versionGraph(id,version)};});
  app.post('/admin/api/v2/content-documents/:id/versions',async request=>{const admin=requirePermission(request,'content:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({graph:dialogGraphSchema,changeNote:z.string().max(300).optional()}).parse(request.body);const result=await saveDraft(admin.id,id,b.graph,b.changeNote);await writeAudit(admin,'content.version.create','content_document',id,result,request);return result;});
  app.post('/admin/api/v2/content-documents/:id/publish',async request=>{const admin=requirePermission(request,'content:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({version:z.number().int().positive(),testAudience:z.record(z.unknown()).default({})}).parse(request.body);const result=await publishVersion(admin.id,id,b.version,b.testAudience);await writeAudit(admin,'content.publish','content_document',id,b,request);return result;});
  app.post('/admin/api/v2/content-documents/:id/rollback',async request=>{const admin=requirePermission(request,'content:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({version:z.number().int().positive()}).parse(request.body);const result=await rollbackVersion(admin.id,id,b.version);await writeAudit(admin,'content.rollback','content_document',id,b,request);return result;});

  app.get('/admin/api/v2/experiments',async request=>{requirePermission(request,'analytics:read');const[e,v,a]=await Promise.all([pool.query(`SELECT * FROM ab_experiments ORDER BY created_at DESC`),pool.query(`SELECT * FROM ab_variants ORDER BY experiment_id,key`),pool.query(`SELECT experiment_id,variant_id,COUNT(*)::int users FROM user_experiment_assignments GROUP BY experiment_id,variant_id`)]);return{experiments:e.rows,variants:v.rows,assignments:a.rows};});
  app.post('/admin/api/v2/experiments',async request=>{const admin=requirePermission(request,'settings:write');const b=z.object({key:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(2).max(120),description:z.string().max(500),allocation:z.number().int().min(1).max(100),variants:z.array(z.object({key:z.string().regex(/^[a-z0-9-]+$/),weight:z.number().int().positive(),config:z.record(z.unknown())})).min(2).max(10)}).parse(request.body);const id=crypto.randomUUID();await withTransaction(async client=>{await client.query(`INSERT INTO ab_experiments(id,key,title,description,status,allocation,starts_at) VALUES($1,$2,$3,$4,'draft',$5,NULL)`,[id,b.key,b.title,b.description,b.allocation]);for(const variant of b.variants)await client.query(`INSERT INTO ab_variants(id,experiment_id,key,weight,config) VALUES($1,$2,$3,$4,$5)`,[crypto.randomUUID(),id,variant.key,variant.weight,JSON.stringify(variant.config)]);});await writeAudit(admin,'experiment.create','ab_experiment',id,b,request);return{id};});
  app.patch('/admin/api/v2/experiments/:id',async request=>{const admin=requirePermission(request,'settings:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({status:z.enum(['draft','running','paused','completed']).optional(),allocation:z.number().int().min(1).max(100).optional(),endsAt:z.string().datetime().optional().nullable()}).parse(request.body);await pool.query(`UPDATE ab_experiments SET status=COALESCE($2,status),allocation=COALESCE($3,allocation),starts_at=CASE WHEN $2='running' THEN COALESCE(starts_at,NOW()) ELSE starts_at END,ends_at=CASE WHEN $4::boolean THEN $5::timestamptz ELSE ends_at END,updated_at=NOW() WHERE id=$1`,[id,b.status??null,b.allocation??null,Object.prototype.hasOwnProperty.call(b,'endsAt'),b.endsAt??null]);await writeAudit(admin,'experiment.update','ab_experiment',id,b,request);return{ok:true};});

  app.get('/admin/api/v2/backups',async request=>{requirePermission(request,'settings:read');return{items:(await pool.query(`SELECT * FROM backup_runs ORDER BY started_at DESC LIMIT 100`)).rows};});
  app.post('/admin/api/v2/backups',async request=>{const admin=requirePermission(request,'settings:write');const result=await createBackup('manual');await writeAudit(admin,'backup.create','backup_run',result.id,{path:result.path,size:result.size},request);return result;});
  app.patch('/admin/api/v2/backups/:id/verified',async request=>{const admin=requirePermission(request,'settings:write');const{id}=z.object({id:uuid}).parse(request.params);await pool.query(`UPDATE backup_runs SET verified_at=NOW() WHERE id=$1 AND status='completed'`,[id]);await writeAudit(admin,'backup.verify','backup_run',id,{},request);return{ok:true};});

  app.get('/admin/api/v2/realtime',async request=>{requirePermission(request,'operations:read');const[matches,presence]=await Promise.all([pool.query(`SELECT m.id,m.code,m.status,m.max_players,m.scenario_sku,m.created_at,m.started_at,m.updated_at,u.first_name host_name,(SELECT COUNT(*) FROM coop_members c WHERE c.match_id=m.id AND c.left_at IS NULL)::int members FROM coop_matches m LEFT JOIN users u ON u.id=m.host_id ORDER BY m.updated_at DESC LIMIT 200`),pool.query(`SELECT COUNT(*)::int recently_seen FROM player_profiles WHERE last_seen>NOW()-INTERVAL '2 minutes'`)]);return{matches:matches.rows,presence:presence.rows[0],redis:await redisHealth()};});
  app.post('/admin/api/v2/realtime/:id/cancel',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);await pool.query(`UPDATE coop_matches SET status='cancelled',completed_at=NOW(),updated_at=NOW() WHERE id=$1 AND status IN ('lobby','playing')`,[id]);const redis=await getRedis();if(redis){const raw=await redis.get(`coop:match:${id}`);if(raw){const state=JSON.parse(raw);state.phase='cancelled';await redis.set(`coop:match:${id}`,JSON.stringify(state),{EX:3600});await redis.sRem('coop:active',id);}}await writeAudit(admin,'realtime.cancel','coop_match',id,{},request);return{ok:true};});

  app.get('/admin/api/v2/observability',async request=>{requirePermission(request,'dashboard:read');const[db,queues,payments]=await Promise.all([pool.query(`SELECT (SELECT COUNT(*) FROM pg_stat_activity WHERE datname=current_database())::int connections,pg_database_size(current_database())::bigint database_bytes`),pool.query(`SELECT status,COUNT(*)::int count FROM broadcast_deliveries GROUP BY status`),pool.query(`SELECT status,COUNT(*)::int count FROM purchases WHERE created_at>NOW()-INTERVAL '24 hours' GROUP BY status`)]);return{database:db.rows[0],queues:queues.rows,payments:payments.rows,redis:await redisHealth(),metrics:await registry.metrics()};});
}
