import crypto from 'node:crypto';
import type { FastifyInstance,FastifyRequest } from 'fastify';
import { z } from 'zod';
import { pool } from '../db.js';
import { AppError } from '../errors.js';
import { hasPermission,type AdminPrincipal,type Permission } from './rbac.js';
import { writeAudit } from './audit.js';
function adminOf(request:FastifyRequest):AdminPrincipal{return(request as any).adminPrincipal;}
function requirePermission(request:FastifyRequest,p:Permission){const a=adminOf(request);if(!hasPermission(a,p))throw new AppError('Недостаточно прав',403);return a;}
const uuid=z.string().uuid();
export async function adminV4Routes(app:FastifyInstance){
 app.get('/admin/api/v4/overview',async request=>{requirePermission(request,'operations:read');const [traces,cases,nights,voices,rooms,relations,payment,content,emoji,antagonists]=await Promise.all([
  pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE created_at>NOW()-INTERVAL '24 hours')::int today FROM room_traces WHERE expires_at>NOW()`),
  pool.query(`SELECT status,COUNT(*)::int count FROM chat_cases GROUP BY status`),pool.query(`SELECT * FROM live_nights ORDER BY starts_at DESC LIMIT 20`),
  pool.query(`SELECT v.id,v.phrase_key,v.mime_type,v.duration_ms,v.status,v.created_at,u.first_name,u.username FROM neighbor_voice_clips v JOIN users u ON u.id=v.user_id WHERE v.status<>'deleted' ORDER BY CASE v.status WHEN 'pending' THEN 0 ELSE 1 END,v.created_at DESC LIMIT 100`),
  pool.query(`SELECT r.*,u.first_name author_name FROM user_rooms r JOIN users u ON u.id=r.author_id ORDER BY CASE r.status WHEN 'review' THEN 0 ELSE 1 END,r.created_at DESC LIMIT 100`),
  pool.query(`SELECT COUNT(*)::int links,COALESCE(AVG(trust),0)::numeric(10,1) avg_trust,SUM(rescues)::int rescues,SUM(abandonments)::int abandonments FROM player_relationships`),
  pool.query(`SELECT r.*,u.first_name,p.sku FROM payment_support_requests r JOIN users u ON u.id=r.user_id LEFT JOIN purchases p ON p.id=r.purchase_id ORDER BY r.created_at DESC LIMIT 100`),
  pool.query(`SELECT content_type,COUNT(*)::int count FROM content_inventory WHERE active=TRUE GROUP BY content_type`),
  pool.query(`SELECT * FROM emoji_status_catalog ORDER BY key`),
  pool.query(`SELECT a.*,b.title building_name,u.first_name antagonist_name FROM antagonist_cycles a JOIN buildings b ON b.id=a.building_id LEFT JOIN users u ON u.id=a.antagonist_user_id ORDER BY a.week_start DESC LIMIT 50`)
 ]);return{traces:traces.rows[0],cases:cases.rows,nights:nights.rows,voices:voices.rows,rooms:rooms.rows,relationships:relations.rows[0],paymentSupport:payment.rows,content:content.rows,emoji:emoji.rows,antagonists:antagonists.rows};});
 app.patch('/admin/api/v4/voices/:id',async request=>{const admin=requirePermission(request,'operations:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({status:z.enum(['approved','rejected'])}).parse(request.body);await pool.query(`UPDATE neighbor_voice_clips SET status=$2,moderator_id=$3,reviewed_at=NOW() WHERE id=$1 AND status='pending'`,[id,b.status,admin.id]);await writeAudit(admin,'voice.review','neighbor_voice',id,b,request);return{ok:true};});
 app.patch('/admin/api/v4/user-rooms/:id',async request=>{const admin=requirePermission(request,'content:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({status:z.enum(['published','rejected','archived']),note:z.string().max(500).optional()}).parse(request.body);await pool.query(`UPDATE user_rooms SET status=$2,moderation_note=$3,published_at=CASE WHEN $2='published' THEN NOW() ELSE published_at END,updated_at=NOW() WHERE id=$1`,[id,b.status,b.note??null]);await writeAudit(admin,'user-room.review','user_room',id,b,request);return{ok:true};});
 app.post('/admin/api/v4/live-nights',async request=>{const admin=requirePermission(request,'content:write');const b=z.object({title:z.string().min(3).max(120),startsAt:z.string().datetime(),durationMinutes:z.number().int().min(10).max(180),target:z.number().int().min(10).max(100000),config:z.record(z.unknown()).default({})}).parse(request.body);const id=crypto.randomUUID(),key=`night-${new Date(b.startsAt).toISOString().slice(0,10)}-${id.slice(0,5)}`;await pool.query(`INSERT INTO live_nights(id,event_key,title,starts_at,ends_at,global_target,config) VALUES($1,$2,$3,$4,$4::timestamptz+($5||' minutes')::interval,$6,$7)`,[id,key,b.title,b.startsAt,b.durationMinutes,b.target,JSON.stringify(b.config)]);await writeAudit(admin,'live-night.create','live_night',id,b,request);return{id};});
 app.patch('/admin/api/v4/emoji/:key',async request=>{const admin=requirePermission(request,'settings:write');const{key}=z.object({key:z.string().min(1).max(60)}).parse(request.params);const b=z.object({customEmojiId:z.string().max(100).nullable(),durationSeconds:z.number().int().positive().nullable().optional(),active:z.boolean().optional()}).parse(request.body);await pool.query(`UPDATE emoji_status_catalog SET custom_emoji_id=$2,duration_seconds=COALESCE($3,duration_seconds),active=COALESCE($4,active) WHERE key=$1`,[key,b.customEmojiId,b.durationSeconds??null,b.active??null]);await writeAudit(admin,'emoji.update','emoji_status',key,b,request);return{ok:true};});
 app.patch('/admin/api/v4/payment-support/:id',async request=>{const admin=requirePermission(request,'purchases:write');const{id}=z.object({id:uuid}).parse(request.params);const b=z.object({status:z.enum(['open','reviewing','resolved'])}).parse(request.body);await pool.query(`UPDATE payment_support_requests SET status=$2,resolved_at=CASE WHEN $2='resolved' THEN NOW() ELSE resolved_at END WHERE id=$1`,[id,b.status]);await writeAudit(admin,'payment-support.update','payment_support',id,b,request);return{ok:true};});
 app.delete('/admin/api/v4/traces/expired',async request=>{const admin=requirePermission(request,'operations:write');const r=await pool.query(`DELETE FROM room_traces WHERE expires_at<=NOW() RETURNING id`);await writeAudit(admin,'trace.purge','room_trace',null,{count:r.rowCount},request);return{deleted:r.rowCount};});
}
