import crypto from 'node:crypto';
import { config } from './config.js';
import { pool, withTransaction } from './db.js';
import { applyGrantConfig, revokeGrantConfig } from './shop-service.js';
import { AppError } from './errors.js';
import { paymentEvents, telegramErrors } from './observability/metrics.js';

const api=`https://api.telegram.org/bot${config.BOT_TOKEN}`;
export async function callTelegram<T>(method:string,body:Record<string,unknown>):Promise<T>{try{const response=await fetch(`${api}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const json=await response.json() as{ok:boolean;result?:T;description?:string;parameters?:{retry_after?:number}};if(!json.ok)throw new AppError(`Telegram ${method}: ${json.description??'unknown error'}`,502,'TELEGRAM_API_ERROR');return json.result as T;}catch(error){telegramErrors.inc({method});throw error;}}
export async function configureTelegram():Promise<void>{if(!config.PUBLIC_URL)return;const webhookUrl=`${config.PUBLIC_URL.replace(/\/$/,'')}/telegram/webhook`;const info=await callTelegram<{url:string}>('getWebhookInfo',{});if(info.url!==webhookUrl)await callTelegram('setWebhook',{url:webhookUrl,secret_token:config.WEBHOOK_SECRET,allowed_updates:['message','pre_checkout_query']});const currentMenu=await callTelegram<any>('getChatMenuButton',{});if(currentMenu?.type!=='web_app'||currentMenu?.web_app?.url!==config.PUBLIC_URL)await callTelegram('setChatMenuButton',{menu_button:{type:'web_app',text:'Открыть дом',web_app:{url:config.PUBLIC_URL}}});}
async function productForInvoice(sku:string){const found=await pool.query(`SELECT sku,title,description,stars,available_from,available_until,active FROM shop_products WHERE sku=$1`,[sku]);const item=found.rows[0];if(!item||!item.active||(item.available_from&&new Date(item.available_from)>new Date())||(item.available_until&&new Date(item.available_until)<=new Date()))throw new AppError('Товар недоступен',404,'SHOP_PRODUCT_UNAVAILABLE');return item;}
export async function createStarsInvoice(userId:number,sku:string,metadata:Record<string,unknown>={}):Promise<{invoiceLink:string;purchaseId:string}>{const item=await productForInvoice(sku);const id=crypto.randomUUID();await pool.query(`INSERT INTO purchases(id,user_id,sku,stars,status,metadata) VALUES($1,$2,$3,$4,'pending',$5)`,[id,userId,sku,item.stars,JSON.stringify(metadata)]);const invoiceLink=await callTelegram<string>('createInvoiceLink',{title:item.title,description:item.description,payload:id,currency:'XTR',prices:[{label:item.title,amount:Number(item.stars)}]});paymentEvents.inc({status:'invoice',sku});return{invoiceLink,purchaseId:id};}
export async function createGiftInvoice(userId:number,targetId:number,sku:string,message:string,anonymous:boolean){if(userId===targetId)throw new AppError('Для себя используйте обычную покупку',400,'GIFT_SELF');const target=await pool.query(`SELECT 1 FROM users WHERE id=$1`,[targetId]);if(!target.rowCount)throw new AppError('Получатель не найден',404,'GIFT_TARGET_NOT_FOUND');const known=await pool.query(`SELECT 1 WHERE EXISTS(SELECT 1 FROM building_members a JOIN building_members b ON b.building_id=a.building_id WHERE a.user_id=$1 AND b.user_id=$2) OR EXISTS(SELECT 1 FROM neighbor_notes WHERE (author_id=$1 AND target_id=$2) OR (author_id=$2 AND target_id=$1)) OR EXISTS(SELECT 1 FROM users WHERE (id=$1 AND referred_by=$2) OR (id=$2 AND referred_by=$1))`,[userId,targetId]);const result=await createStarsInvoice(userId,sku,{giftTargetId:targetId,giftMessage:message,giftAnonymous:anonymous,giftStranger:!known.rowCount});const giftId=crypto.randomUUID();await pool.query(`INSERT INTO gifts(id,purchase_id,sender_id,target_id,sku,message,anonymous) VALUES($1,$2,$3,$4,$5,$6,$7)`,[giftId,result.purchaseId,userId,targetId,sku,message||null,anonymous]);return{...result,giftId};}
export async function answerPreCheckout(id:string,ok:boolean,errorMessage?:string):Promise<void>{await callTelegram('answerPreCheckoutQuery',{pre_checkout_query_id:id,ok,...(ok?{}:{error_message:errorMessage})});}
export async function fulfillSuccessfulPayment(message:any):Promise<void>{const payment=message.successful_payment;const purchaseId=payment.invoice_payload;let strangerGiftSender:string|null=null;await withTransaction(async client=>{const found=await client.query(`SELECT p.id,p.user_id::text,p.sku,p.stars,p.status,p.metadata,s.grant_config FROM purchases p LEFT JOIN shop_products s ON s.sku=p.sku WHERE p.id=$1 FOR UPDATE OF p`,[purchaseId]);const purchase=found.rows[0];if(!purchase||purchase.status==='paid')return;if(payment.currency!=='XTR'||Number(payment.total_amount)!==Number(purchase.stars))throw new AppError('Сумма платежа не совпадает со счётом',400,'PAYMENT_MISMATCH');const targetId=purchase.metadata?.giftTargetId?String(purchase.metadata.giftTargetId):purchase.user_id;const granted=await applyGrantConfig(client,targetId,purchase.grant_config??{});await client.query(`UPDATE purchases SET status='paid',telegram_charge_id=$2,provider_charge_id=$3,fulfilled_at=NOW() WHERE id=$1`,[purchaseId,payment.telegram_payment_charge_id,payment.provider_payment_charge_id??null]);await client.query(`INSERT INTO purchase_fulfillments(purchase_id,grants) VALUES($1,$2) ON CONFLICT(purchase_id) DO NOTHING`,[purchaseId,JSON.stringify({...granted,targetUserId:targetId})]);await client.query(`UPDATE player_profiles SET stars_spent=stars_spent+$2 WHERE user_id=$1`,[purchase.user_id,purchase.stars]);if(purchase.metadata?.giftTargetId)await client.query(`UPDATE gifts SET status='delivered' WHERE purchase_id=$1`,[purchaseId]);if(purchase.metadata?.giftTargetId&&purchase.metadata?.giftStranger)strangerGiftSender=purchase.user_id;await client.query(`INSERT INTO analytics_events(user_id,event_name,properties) VALUES($1,'purchase_paid',$2)`,[purchase.user_id,JSON.stringify({purchaseId,sku:purchase.sku,stars:Number(purchase.stars),gift:Boolean(purchase.metadata?.giftTargetId)})]);paymentEvents.inc({status:'paid',sku:purchase.sku});});if(strangerGiftSender)await pool.query(`INSERT INTO user_achievements(achievement_id,user_id,context) SELECT id,$1,$2 FROM achievements WHERE slug='stranger-gift' ON CONFLICT DO NOTHING`,[strangerGiftSender,JSON.stringify({purchaseId})]);}
export async function restorePurchase(userId:string|number,purchaseId:string){return withTransaction(async client=>{const found=await client.query(`SELECT p.*,s.grant_config,pf.purchase_id fulfillment_id FROM purchases p LEFT JOIN shop_products s ON s.sku=p.sku LEFT JOIN purchase_fulfillments pf ON pf.purchase_id=p.id WHERE p.id=$1 AND p.user_id=$2 FOR UPDATE OF p`,[purchaseId,userId]);const row=found.rows[0];if(!row||row.status!=='paid')throw new AppError('Подтверждённая покупка не найдена',404,'PAID_PURCHASE_NOT_FOUND');if(row.fulfillment_id)return{restored:false,reason:'already_fulfilled'};const targetId=row.metadata?.giftTargetId?String(row.metadata.giftTargetId):String(userId);const grants=await applyGrantConfig(client,targetId,row.grant_config??{});await client.query(`INSERT INTO purchase_fulfillments(purchase_id,grants) VALUES($1,$2)`,[purchaseId,JSON.stringify({...grants,targetUserId:targetId})]);return{restored:true};});}
export async function refundPurchase(purchaseId:string):Promise<void>{const purchase=await pool.query(`SELECT id,user_id::text,stars,status,telegram_charge_id FROM purchases WHERE id=$1`,[purchaseId]);const row=purchase.rows[0];if(!row)throw new AppError('Покупка не найдена',404,'PURCHASE_NOT_FOUND');if(row.status!=='paid'||!row.telegram_charge_id)throw new AppError('Вернуть можно только подтверждённый платёж',409,'PURCHASE_NOT_REFUNDABLE');await callTelegram<boolean>('refundStarPayment',{user_id:Number(row.user_id),telegram_payment_charge_id:row.telegram_charge_id});await withTransaction(async client=>{const locked=await client.query(`SELECT p.user_id::text,p.stars,p.status,p.sku,p.metadata,pf.grants,s.grant_config FROM purchases p LEFT JOIN purchase_fulfillments pf ON pf.purchase_id=p.id LEFT JOIN shop_products s ON s.sku=p.sku WHERE p.id=$1 FOR UPDATE OF p`,[purchaseId]);const current=locked.rows[0];if(!current||current.status==='refunded')return;const targetId=current.grants?.targetUserId??current.metadata?.giftTargetId??current.user_id;await revokeGrantConfig(client,targetId,current.grants??current.grant_config??{});await client.query(`UPDATE purchases SET status='refunded' WHERE id=$1`,[purchaseId]);await client.query(`UPDATE purchase_fulfillments SET revoked_at=NOW() WHERE purchase_id=$1`,[purchaseId]);await client.query(`UPDATE gifts SET status='refunded' WHERE purchase_id=$1`,[purchaseId]);await client.query(`UPDATE player_profiles SET stars_spent=GREATEST(0,stars_spent-$2) WHERE user_id=$1`,[current.user_id,current.stars]);paymentEvents.inc({status:'refunded',sku:current.sku});});}
export async function sendBotMessage(chatId:string|number,text:string,buttonText?:string|null,buttonUrl?:string|null):Promise<void>{await callTelegram('sendMessage',{chat_id:chatId,text,disable_web_page_preview:true,...(buttonText&&buttonUrl?{reply_markup:{inline_keyboard:[[{text:buttonText,url:buttonUrl}]]}}:{})});}
export async function getBotStarBalance():Promise<unknown>{return callTelegram('getMyStarBalance',{});}export async function getBotStarTransactions(offset=0,limit=50):Promise<unknown>{return callTelegram('getStarTransactions',{offset,limit});}
export async function sendWelcome(chatId:number,firstName:string):Promise<void>{if(!config.PUBLIC_URL)return;await callTelegram('sendMessage',{chat_id:chatId,text:`Добро пожаловать, ${firstName}. Лифт уже остановился между седьмым и девятым этажами.`,reply_markup:{inline_keyboard:[[{text:'Открыть двери лифта',web_app:{url:config.PUBLIC_URL}}]]}});}
